-- =============================================================================
-- Migration 052 — Podium Background-Removed Photos
--
-- Adds a dedicated podium_photo_url column to employees, written by the
-- remove-background Edge Function when the leaderboard refreshes.
-- Updates get_leaderboard() to surface avatar_url, job_title and
-- podium_photo_url so the TopThreePodium component can use them.
--
-- Why a separate column?
--   • photo_url is the employee's raw upload (used everywhere else).
--   • podium_photo_url is the background-removed PNG (generated once per
--     leaderboard refresh, only for the top 3).  Keeping them separate
--     prevents the podium process from touching every employee's avatar.
-- =============================================================================


-- ─── 1. New column ────────────────────────────────────────────────────────────

ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS podium_photo_url text;

COMMENT ON COLUMN public.employees.podium_photo_url IS
  'Public URL of the transparent-background PNG generated by the remove.bg API. '
  'Written by the remove-background Edge Function during the weekly leaderboard '
  'refresh — only populated for the current top-3 podium employees. '
  'NULL means the raw photo_url (or placeholder) should be used instead.';


-- ─── 2. Rebuild get_leaderboard() — add avatar / job / podium columns ─────────

DROP FUNCTION IF EXISTS public.get_leaderboard(text, timestamptz, timestamptz, integer);

CREATE OR REPLACE FUNCTION public.get_leaderboard(
  p_hotel  text,
  p_start  timestamptz DEFAULT NULL,
  p_end    timestamptz DEFAULT NULL,
  p_limit  integer     DEFAULT 50
)
RETURNS TABLE (
  rank              bigint,
  employee_id       uuid,
  full_name         text,
  employee_code     text,
  total_points      bigint,
  points_balance    integer,
  job_title         text,
  avatar_url        text,       -- raw profile photo
  podium_photo_url  text        -- background-removed PNG (top 3 only)
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    ROW_NUMBER() OVER (ORDER BY COALESCE(SUM(pl.points), 0) DESC)  AS rank,
    e.id                                                            AS employee_id,
    e.full_name,
    e.employee_code,
    COALESCE(SUM(pl.points), 0)                                    AS total_points,
    e.points_balance,
    e.job_title,
    e.photo_url                                                     AS avatar_url,
    e.podium_photo_url
  FROM  public.employees e
  LEFT  JOIN public.points_ledger pl
         ON  pl.employee_id = e.id
        AND  pl.hotel       = e.hotel
        AND  (p_start IS NULL OR pl.created_at >= p_start)
        AND  (p_end   IS NULL OR pl.created_at <  p_end)
  WHERE e.hotel  = p_hotel
    AND e.status = 'active'
  GROUP BY e.id, e.full_name, e.employee_code, e.points_balance,
           e.job_title, e.photo_url, e.podium_photo_url
  HAVING COALESCE(SUM(pl.points), 0) > 0
  ORDER BY total_points DESC
  LIMIT  p_limit;
$$;

GRANT EXECUTE ON FUNCTION public.get_leaderboard(text, timestamptz, timestamptz, integer)
  TO anon;
GRANT EXECUTE ON FUNCTION public.get_leaderboard(text, timestamptz, timestamptz, integer)
  TO authenticated;

COMMENT ON FUNCTION public.get_leaderboard IS
  'Returns hotel-scoped ranked employees by points earned within an optional date window.
   Computes live from employees JOIN points_ledger — no cache table.
   p_start / p_end = NULL → all-time ranking.
   Employees with zero points in the selected period are excluded.
   Now returns job_title, avatar_url (photo_url) and podium_photo_url.';
